name: palm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pip
  - numpy=1.21.6
  - pandas=1.3.5
  - matplotlib=3.1.3
  - scipy=1.4.1
  - scikit-learn=0.22.1
  - pip:
    - torch==1.10.0
    - xgboost==1.5.2